return {
	"nvimdev/dashboard-nvim",
	event = "VimEnter",
	config = function()
		require('dashboard').setup({
			theme = "hyper",
			diassable_move = false,
			shortcut_type = "number",
			config = {
				--weak_header = { enable = true },
				shortcut = {},
				packages = { enable = false },
				project = { enable = false },
				mru = { enable = false, limit = 9, icon = "", label = "", cwd_only = false},
				--footer = { tostring(vim.fn.system( "" ):gsub("\n"," ")) },
				footer = { "" },

				header = {	
[[                        ____                        ]],
[[                       |    |                       ]],
[[                   ____|    |____                   ]],
[[                  |Jesus, King of|                  ]],
[[                  |   The Jews   |                  ]],
[[                  '""""|    |""""'                  ]],
[[        _______________|  xxxx______________        ]],
[[       |         /_;'-._  / _\  _.-;_\      |       ]],
[[       |           *-._`'`_/'`.-'           |       ]],
[[       '"""""""""""""""|`\   /`"""""""""""""'       ]],
[[                       | |  /                       ]],
[[                       |/-.(|                       ]],
[[                       |\_._\                       ]],
[[                       | \ \`;                      ]],
[[                 <>._  |  > |/                      ]],
[[                 <>. '<  / //                       ]],
[[                    *.<  |//|                       ]],
[[                       | \(\ >._                    ]],
[[                       |     >. '<>                 ]],
[[                       |    |  *.<>                 ]],
[[                       |    |                       ]],
[[                       |    |                       ]],
[[                                                    ]],
[[																									  ]],
[[                       John 19                      ]],
[[																									  ]],
[[  28 After this, Jesus knowing that all things      ]], 
[[were now accomplished, that the scripture           ]],
[[might be fulfilled, saith, I thirst.                ]],
[[  29 Now there was set a vessel full of vinegar:    ]],
[[and they filled a spunge with vinegar,              ]],
[[and put it upon hyssop, and put it to his mouth.    ]],
[[  30 When Jesus therefore had received the vinegar, ]],
[[he said, It is finished: and he bowed his head,     ]],
[[and gave up the ghost.                              ]],
				},
			}
		})
	end,
	dependencies = {{ "nvim-tree/nvim-web-devicons" }}
}
